swagger: '2.0'
info:
  title: API Title
  version: '1.0'
host: api.server.test
basePath: /
schemes:
  - https
paths:

  /api/update:
    post:
      summary: "Post update configuration"
      tags:
      - "global"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/system:
    get:
      summary: "Get system information"
      tags:
      - "global"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers:
    get:
      summary: "Get all servers"
      tags:
      - "global"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
    post:
      summary: "Post create server"
      tags:
      - "global"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/transfer:
    post:
      summary: "Post transfer"
      tags:
      - "global"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
            


  /api/servers/{server}:
    get:
      summary: "Get the server"
      tags:
      - "server"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
    delete:
      summary: "Delete the server"
      tags:
      - "server"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
    patch:
      summary: "Patch the server"
      tags:
      - "server"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"

  /api/servers/{server}/logs:
    get:
      summary: "Get server logs"
      tags:
      - "server"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/power:
    post:
      summary: "Post server power"
      tags:
      - "server"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/commands:
    post:
      summary: "Post server commands"
      tags:
      - "server"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/install:
    post:
      summary: "Post server install"
      tags:
      - "server"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/reinstall:
    post:
      summary: "Post server reinstall"
      tags:
      - "server"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/ws/deny:
    post:
      summary: "Post server deny WS tokens"
      tags:
      - "server"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/archive:
    post:
      summary: "Post server archive"
      description: "This archive request causes the archive to start being created this should only be triggered by the panel."
      tags:
      - "server"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/files/contents:
    get:
      summary: "Get server file contents"
      tags:
      - "files"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/files/list-directory:
    get:
      summary: "Get server list directory"
      tags:
      - "files"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/files/rename:
    put:
      summary: "Put server rename files"
      tags:
      - "files"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/files/copy:
    post:
      summary: "Post server copy file"
      tags:
      - "files"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/files/write:
    post:
      summary: "Post server write file"
      tags:
      - "files"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/files/create-directory:
    post:
      summary: "Post server create directory"
      tags:
      - "files"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/files/delete:
    post:
      summary: "Post server delete files"
      tags:
      - "files"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/files/compress:
    post:
      summary: "Post server compress files"
      tags:
      - "files"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/files/decompress:
    post:
      summary: "Post server decompress files"
      tags:
      - "files"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/files/chmod:
    post:
      summary: "Post server chmod file"
      tags:
      - "files"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/files/pull:
    get:
      summary: "Get server pulling files"
      tags:
      - "files"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
    post:
      summary: "Post server pull remote file"
      tags:
      - "files"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/files/pull/{download}:
    get:
      summary: "Get server pulling files"
      tags:
      - "files"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64" 
      - name: "download"
        in: "path"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"


  /api/servers/{server}/backup:
    post:
      summary: "Post server backup"
      tags:
      - "backup"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/backup/{backup}/restore:
    post:
      summary: "Post server restore backup"
      tags:
      - "backup"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      - name: "backup"
        in: "path"
        description: "ID of backup"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"
  /api/servers/{server}/backup/{backup}:
    delete:
      summary: "Delete server backup"
      tags:
      - "backup"
      parameters:
      - name: "server"
        in: "path"
        description: "ID of server"
        required: true
        type: "string"
        format: "int64"
      - name: "backup"
        in: "path"
        description: "ID of backup"
        required: true
        type: "string"
        format: "int64"
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/ApiResponse"



definitions:
    ApiResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
        type:
          type: "string"
        message:
          type: "string"  